config/routes.rb
Rails.application.routes.draw do
  # get 'students/index'
  # get 'students/show'
  # get 'students/new'
  # get 'students/edit'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "students#index"

  resources :students 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
# def index
#     @students = Student.all
#   end

#   def show
#     @student = Student.find(params[:id])
#   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    student = Student.create(student_params)
    redirect_to students_path
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update 
    @student = Student.find(params[:id])
    @student.update(student_params)
    redirect_to student_path
  end

  def destroy 
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to student_path
  end

  private 
  def student_params 
    params.require(:student).permit(:name , :age, :enroll_number, :branch)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentIdApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

<%= form_with model: @student  do |f| %>
<%= f.text_field :name, placeholder: "enter your name" %>
<%= f.text_field :age, placeholder: "enter your age" %>
<%= f.text_field :enroll_number, placeholder: "enter your enroll_number" %>
<%= f.text_field :branch, placeholder: "enter your branch" %>
<%= f.submit %>
<% end %>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>

<table>
  <% @students.each do |std| %>
    <tr>
      <td><%= link_to std.name, student_path(std)%></td>
      <td><%= link_to "Edit", edit_student_path(std) %></td>
      <td><%= button_to "Delete", student_path(std), method: :delete, data: { turbo_confirm: 'Are you sure?' } %><td>
    </tr>
  <% end %>
  <tr>
    <%= link_to "Add New Student", new_student_path	%>
  </tr>
</table>

app/views/students/new.html.erb
<h1>Students#new</h1>
<p>Find me in app/views/students/new.html.erb</p>

<%= form_with model: @student  do |f| %>
<%= f.text_field :name, placeholder: "enter your name" %>
<%= f.text_field :age, placeholder: "enter your age" %>
<%= f.text_field :enroll_number, placeholder: "enter your enroll_number" %>
<%= f.text_field :branch, placeholder: "enter your branch" %>
<%= f.submit %>
<% end %>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>

<h3><%= @student.name %></h3>
<h3><%= @student.age %></h3>
<h3 ><%= @student.enroll_number %></h3>
<h3 ><%= @student.branch %></h3>